version: "3.6"
services:
  icinga2:
    build: ../../image
    image: icinga2:latest
    container_name: icinga2
    restart: on-failure
    ports:
      - "8080:80"
      - "8443:443"
      - "5665:5665"