version: "3.6"
services:
  icinga2:
    build: ../../image
    image: icinga2:latest
    container_name: icinga2
    restart: on-failure
    environment:
      - ICINGAWEB2_ADMIN_USER=icingaadmin
      - ICINGAWEB2_ADMIN_PASSWORD=secret-pw
      - PHP_TIMEZONE=Europe/Paris
    ports:
      - "80:80"
      - "443:443"
      - "5665:5665"