#!/bin/bash

PATH_ICINGAWEB2=/etc/icingaweb2
SRC_ICINGAWEB2=/etc/icingaweb2.orig

ICINGAWEB2_DB_HOST=${ICINGAWEB2_DB_HOST:="${DB_HOST}"}
ICINGAWEB2_DB_PORT=${ICINGAWEB2_DB_PORT:="${DB_PORT}"}
ICINGAWEB2_DB_DATABASE=${ICINGAWEB2_DB_DATABASE:="icingaweb2"}
ICINGAWEB2_DB_USER=${ICINGAWEB2_DB_USER:="icingaweb2"}
ICINGAWEB2_DB_CHARSET=${ICINGAWEB2_DB_CHARSET:="latin1"}
ICINGAWEB2_DB_PERSISTENT=${ICINGAWEB2_DB_PERSISTENT:=0}
ICINGAWEB2_DB_USE_SSL=${ICINGAWEB2_DB_USE_SSL:=0}

if [ -z "$(ls -A $PATH_ICINGAWEB2)" ]; then
	echo "=> Copying fresh files for icingaweb2"
    cp -r $SRC_ICINGAWEB2/* $PATH_ICINGAWEB2
fi

mkdir -p /var/log/icingaweb2
chown -R www-data:adm /var/log/icingaweb2

# Create Icingaweb2 database
db_create_database                                              \
        ${ICINGAWEB2_DB_HOST}                                   \
        ${ICINGAWEB2_DB_PORT}                                   \
        ${DB_ROOT_USER}                                         \
        ${DB_ROOT_PASSWORD}                                     \
        ${ICINGAWEB2_DB_DATABASE}                               \
        ${ICINGAWEB2_DB_CHARSET}                                \
        "/usr/share/icingaweb2/etc/schema/${DB_TYPE}.schema.sql";

# Create database user for Icingaweb2 database
db_create_user                                                  \
        ${ICINGAWEB2_DB_HOST}                                   \
        ${ICINGAWEB2_DB_PORT}                                   \
        ${DB_ROOT_USER}                                         \
        ${DB_ROOT_PASSWORD}                                     \
        ${ICINGAWEB2_DB_DATABASE}                               \
        ${ICINGAWEB2_DB_USER}                                   \
        ${ICINGAWEB2_DB_PASSWORD}


if [ -z "$(ls -A $PATH_ICINGAWEB2/resources.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/resources.ini" <<-END
[icingaweb_db]
type = "db"
db = "${DB_TYPE}"
host = "${ICINGAWEB2_DB_HOST}"
port = "${ICINGAWEB2_DB_PORT}"
dbname = "${ICINGAWEB2_DB_DATABASE}"
username = "${ICINGAWEB2_DB_USER}"
password = "${ICINGAWEB2_DB_PASSWORD}"
charset = "${ICINGAWEB2_DB_CHARSET}"
persistent = "${ICINGAWEB2_DB_PERSISTENT}"
use_ssl = "${ICINGAWEB2_DB_USE_SSL}"

[icinga_ido]
type = "db"
db = "${DB_TYPE}"
host = "${ICINGA2_DB_IDO_HOST}"
port = "${ICINGA2_DB_IDO_PORT}"
dbname = "${ICINGA2_DB_IDO_DATABASE}"
username = "${ICINGA2_DB_IDO_USER}"
password = "${ICINGA2_DB_IDO_PASSWORD}"
charset = "${ICINGA2_DB_IDO_CHARSET}"
persistent = "${ICINGA2_DB_IDO_PERSISTENT}"
use_ssl = "${ICINGA2_DB_IDO_USE_SSL}"
END

fi

# Icingaweb2 Admin configuration
if [ -z ${ICINGAWEB2_ADMIN_USER+x} ];then ICINGAWEB2_ADMIN_USER="icingaadmin"; fi
if [ -z ${ICINGAWEB2_ADMIN_PASSWORD+x} ];then ICINGAWEB2_ADMIN_PASSWORD="changeme"; fi

# authentication.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/authentication.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/authentication.ini" <<-END
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
END

fi

# config.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/config.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/config.ini" <<-END
[global]
show_stacktraces = "1"
config_backend = "db"
config_resource = "icingaweb_db"

[logging]
log = "php"
level = "ERROR"
application = "icingaweb2"
END

fi

# groups.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/groups.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/groups.ini" <<-END
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
END

fi

# roles.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/roles.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/roles.ini" <<-END
[Administrators]
users = "${ICINGAWEB2_ADMIN_USER}"
permissions = "*"
groups = "Administrators"
END

fi

# Admin account
ICINGAWEB2_ADMIN_PASSWORD_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASSWORD}")

db_insert_admin_user                    \
    ${DB_HOST}                          \
    ${DB_PORT}                          \
    ${DB_ROOT_USER}                     \
    ${DB_ROOT_PASSWORD}                 \
    ${ICINGAWEB2_DB_DATABASE}           \
    ${ICINGAWEB2_ADMIN_USER}            \
    ${ICINGAWEB2_ADMIN_PASSWORD_HASH}

chmod 2770 /etc/icingaweb2
chown -R www-data:icingaweb2 /etc/icingaweb2

head -c 12 /dev/urandom | base64 | tee /etc/icingaweb2/setup.token
chmod 0660 /etc/icingaweb2/setup.token

echo "=>Token: $(cat /etc/icingaweb2/setup.token)"

echo "=>Icingaweb2 setup [OK]"
