#!/bin/bash

if [ -z ${DB_HOST:+x} ]; then 
    echo "=>Icinga2 setup [ERROR]";
    echo "=>Icinga2 ${DB_TYPE} Host not defined";
    exit 1;
fi

if [ -z ${DB_ROOT_PASSWORD:+x} ]; then 
    echo "=>Icinga2 setup [ERROR]";
    echo "=>Icinga2 DB ${DB_TYPE} ROOT password not defined";
    exit 1;
fi

ICINGA2_DB_IDO_HOST=${ICINGA2_DB_IDO_HOST:="${DB_HOST}"}
ICINGA2_DB_IDO_PORT=${ICINGA2_DB_IDO_PORT:=${DB_PORT}}
ICINGA2_DB_IDO_DATABASE=${ICINGA2_DB_IDO_DATABASE:="icinga_ido"}
ICINGA2_DB_IDO_USER=${ICINGA2_DB_IDO_USER:="icinga_ido"}
ICINGA2_DB_IDO_CHARSET=${ICINGA2_DB_IDO_CHARSET:="latin1"}
ICINGA2_DB_IDO_PERSISTENT=${ICINGA2_DB_IDO_PERSISTENT:=0}
ICINGA2_DB_IDO_USE_SSL=${ICINGA2_DB_IDO_USE_SSL:=0}

if [ -z ${ICINGA2_DB_IDO_PASSWORD:+x} ]; then 
    echo "=>Icinga2 IDO setup [ERROR]";
    echo "=>Icinga2 IDO ${DB_TYPE} password not defined";
    exit 1;
fi

DB_OBJECT_NAME="IdoMysqlConnection"

PATH_ICINGA2=/etc/icinga2
SRC_ICINGA2=/etc/icinga2.orig

# Copy configuration files 
if [ -z "$(ls -A $PATH_ICINGA2)" ]; then
	echo "=> Copying fresh config-files for /etc/icinga2"
	cp -R $SRC_ICINGA2/* $PATH_ICINGA2/
fi

mkdir -p    /var/log/icinga2/compat/archives               \
            /var/lib/icinga2/api/{zones,log,repository}    \
            /var/cache/icinga2

chown -R nagios:adm /var/log/icinga2
chown -R nagios:nagios /var/lib/icinga2
chown -R nagios:nagios /var/spool/icinga2
chown -R nagios:nagios /var/cache/icinga2
chown -R nagios:root /etc/icinga2

if [ ${DB_HOST:+x} ]; then

        icinga2 feature enable "ido-${DB_TYPE}"

        # Create Icinga IDO database
        db_create_database                                              \
                ${DB_HOST}                                              \
                ${DB_PORT}                                              \
                ${DB_ROOT_USER}                                         \
                ${DB_ROOT_PASSWORD}                                     \
                ${ICINGA2_DB_IDO_DATABASE}                              \
                ${ICINGA2_DB_IDO_CHARSET}                               \
                "/usr/share/icinga2-ido-${DB_TYPE}/schema/${DB_TYPE}.sql";

        # Create database user for IDO database
        db_create_user                                                  \
                ${DB_HOST}                                              \
                ${DB_PORT}                                              \
                ${DB_ROOT_USER}                                         \
                ${DB_ROOT_PASSWORD}                                     \
                ${ICINGA2_DB_IDO_DATABASE}                              \
                ${ICINGA2_DB_IDO_USER}                                  \
                ${ICINGA2_DB_IDO_PASSWORD}
        
        if [ "${DB_TYPE}" == "pgsql" ]; then
                DB_OBJECT_NAME="IdoPgsqlConnection"
        fi

        cat > /etc/icinga2/features-available/ido-${DB_TYPE}.conf <<-END
library "db_ido_${DB_TYPE}"

object $DB_OBJECT_NAME "ido-${DB_TYPE}" {
user     = "${ICINGA2_DB_IDO_USER}"
password = "${ICINGA2_DB_IDO_PASSWORD}"
host     = "${ICINGA2_DB_IDO_HOST}"
port     =  ${ICINGA2_DB_IDO_PORT}
database = "${ICINGA2_DB_IDO_DATABASE}"
}
END
fi

# enable necessary features
icinga2 feature enable livestatus compatlog command

# enable modules
icingacli module enable monitoring
icingacli module enable doc

#icinga2 API cert - regenerate new private key and certificate when running in a new container
if [ ! -f "/etc/icinga2/pki/$(hostname).key" ]; then
	icinga2 node setup --master
fi

echo "=>Icinga2 setup [OK]"
