#!/bin/bash

PATH_ICINGAWEB2=/etc/icingaweb2
SRC_ICINGAWEB2=/etc/icingaweb2.orig

if [ -z "$(ls -A $PATH_ICINGAWEB2)" ]; then
	echo "=> Copying fresh files for icingaweb2"
    cp -r $SRC_ICINGAWEB2/* $PATH_ICINGAWEB2
fi

mkdir -p /var/log/icingaweb2
chown -R www-data:adm /var/log/icingaweb2

# Create Icingaweb2 database
mysql_create_database                                           \
        ${ICINGAWEB2_MYSQL_HOST}                                \
        "root"                                                  \
        ${MYSQL_ROOT_PASSWORD}                                  \
        ${ICINGAWEB2_MYSQL_DATABASE}                            \
        "/usr/share/icingaweb2/etc/schema/mysql.schema.sql";

# Create database user for Icingaweb2 database
mysql_create_user                                               \
        ${ICINGAWEB2_MYSQL_HOST}                                \
        "root"                                                  \
        ${MYSQL_ROOT_PASSWORD}                                  \
        ${ICINGAWEB2_MYSQL_DATABASE}                            \
        ${ICINGAWEB2_MYSQL_USER}                                \
        ${ICINGAWEB2_MYSQL_PASSWORD}

# Web2 Setup
if [ -z ${ICINGAWEB2_MYSQL_PORT+x} ]; then ICINGAWEB2_MYSQL_PORT=3306; fi
if [ -z ${ICINGAWEB2_MYSQL_DATABASE+x} ]; then ICINGAWEB2_MYSQL_USER="icingaweb2"; fi
if [ -z ${ICINGAWEB2_MYSQL_USER+x} ]; then ICINGAWEB2_MYSQL_USER="icingaweb2"; fi
if [ -z ${ICINGAWEB2_MYSQL_PASSWORD+x} ]; then 
    echo "=>Icingaweb2 setup [ERROR]";
    echo "=>Icingaweb2 MySQL password not defined";
    exit 1;
fi
if [ -z ${ICINGAWEB2_MYSQL_CHARSET+x} ]; then ICINGAWEB2_MYSQL_CHARSET=""; fi
if [ -z ${ICINGAWEB2_MYSQL_PERSISTENT+x} ]; then ICINGAWEB2_MYSQL_PERSISTENT=0; fi
if [ -z ${ICINGAWEB2_MYSQL_USE_SSL+x} ]; then ICINGAWEB2_MYSQL_USE_SSL=0; fi

# IDO Setup
if [ -z ${ICINGA2_MYSQL_IDO_PORT+x} ]; then ICINGA2_MYSQL_IDO_PORT=3306; fi
if [ -z ${ICINGA2_MYSQL_IDO_DATABASE+x} ]; then ICINGA2_MYSQL_IDO_DATABASE="icinga_ido"; fi
if [ -z ${ICINGA2_MYSQL_IDO_USER+x} ]; then ICINGA2_MYSQL_IDO_USER="icinga_ido"; fi
if [ -z ${ICINGA2_MYSQL_IDO_PASSWORD+x} ]; then 
    echo "=>Icinga2 IDO setup [ERROR]";
    echo "=>Icinga2 IDO MySQL password not defined";
    exit 1;
fi
if [ -z ${ICINGA2_MYSQL_IDO_CHARSET+x} ]; then ICINGA2_MYSQL_IDO_CHARSET=""; fi
if [ -z ${ICINGA2_MYSQL_IDO_PERSISTENT+x} ]; then ICINGA2_MYSQL_IDO_PERSISTENT=0; fi
if [ -z ${ICINGA2_MYSQL_IDO_USE_SSL+x} ]; then ICINGA2_MYSQL_IDO_USE_SSL=0; fi

if [ -z "$(ls -A $PATH_ICINGAWEB2/resources.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/resources.ini" <<-END
[icingaweb_db]
type = "db"
db = "mysql"
host = "${ICINGAWEB2_MYSQL_HOST}"
port = "${ICINGAWEB2_MYSQL_PORT}"
dbname = "${ICINGAWEB2_MYSQL_DATABASE}"
username = "${ICINGAWEB2_MYSQL_USER}"
password = "${ICINGAWEB2_MYSQL_PASSWORD}"
charset = "${ICINGAWEB2_MYSQL_CHARSET}"
persistent = "${ICINGAWEB2_MYSQL_PERSISTENT}"
use_ssl = "${ICINGAWEB2_MYSQL_USE_SSL}"

[icinga_ido]
type = "db"
db = "mysql"
host = "${ICINGA2_MYSQL_IDO_HOST}"
port = "${ICINGA2_MYSQL_IDO_PORT}"
dbname = "${ICINGA2_MYSQL_IDO_DATABASE}"
username = "${ICINGA2_MYSQL_IDO_USER}"
password = "${ICINGA2_MYSQL_IDO_PASSWORD}"
charset = "${ICINGA2_MYSQL_IDO_CHARSET}"
persistent = "${ICINGA2_MYSQL_IDO_PERSISTENT}"
use_ssl = "${ICINGA2_MYSQL_IDO_USE_SSL}"
END

fi

# Icingaweb2 Admin configuration
if [ -z ${ICINGAWEB2_ADMIN_USER+x} ];then ICINGAWEB2_ADMIN_USER="icingaadmin"; fi
if [ -z ${ICINGAWEB2_ADMIN_PASSWORD+x} ];then ICINGAWEB2_ADMIN_PASSWORD="Ch4ng3m3!"; fi

# authentication.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/authentication.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/authentication.ini" <<-END
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
END

fi

# config.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/config.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/config.ini" <<-END
[global]
show_stacktraces = "1"
config_backend = "db"
config_resource = "icingaweb_db"

[logging]
log = "php"
level = "ERROR"
application = "icingaweb2"
END

fi

# groups.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/groups.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/groups.ini" <<-END
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
END

fi

# roles.ini
if [ -z "$(ls -A $PATH_ICINGAWEB2/roles.ini 2>/dev/null)" ]; then

    cat > "$PATH_ICINGAWEB2/roles.ini" <<-END
[Administrators]
users = "${ICINGAWEB2_ADMIN_USER}"
permissions = "*"
groups = "Administrators"
END

fi

# Admin account
ICINGAWEB2_ADMIN_PASSWORD_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASSWORD}")
mysql   -h "${MYSQL_HOST}" \
        -u "root" \
        -p"${MYSQL_ROOT_PASSWORD}" \
        "${ICINGAWEB2_MYSQL_DATABASE}" \
        -e "SHOW DATABASES;USE ${ICINGAWEB2_MYSQL_DATABASE}; SHOW TABLES; INSERT IGNORE INTO icingaweb_user (name, active, password_hash) VALUES ('${ICINGAWEB2_ADMIN_USER}', 1, '${ICINGAWEB2_ADMIN_PASSWORD_HASH}');"

chmod 2770 /etc/icingaweb2
chown -R www-data:icingaweb2 /etc/icingaweb2

echo "=>Icingaweb2 setup [OK]"
