#!/bin/bash

# Director Setup
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_TYPE+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_TYPE="${ICINGAWEB2_DB_TYPE}"; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_HOST+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_HOST="${ICINGAWEB2_DB_HOST}"; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_PORT+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_PORT=${ICINGAWEB2_DB_PORT}; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_DATABASE+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_DATABASE="director"; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_USER+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_USER="director"; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_PASSWORD+x} ]; then 
    echo "=>Icingaweb2 Director setup [ERROR]";
    echo "=>Icingaweb2 Director MySQL password not defined";
    exit 1;
fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_CHARSET+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_CHARSET="utf8"; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_PERSISTENT+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_PERSISTENT=${ICINGAWEB2_DB_PERSISTENT}; fi
if [ -z ${ICINGAWEB2_MODULE_DIRECTOR_DB_USE_SSL+x} ]; then ICINGAWEB2_MODULE_DIRECTOR_DB_USE_SSL=${ICINGAWEB2_DB_USE_SSL}; fi

if [ -z ${ICINGA2_API_DIRECTOR_USER+x} ]; then ICINGA2_API_DIRECTOR_USER="director"; fi
if [ -z ${ICINGA2_API_DIRECTOR_PASSWORD+x} ]; then ICINGA2_API_DIRECTOR_PASSWORD="changeme"; fi

# Create director database
db_create_database                                              \
        ${ICINGAWEB2_DB_HOST}                                   \
        ${ICINGAWEB2_DB_PORT}                                   \
        ${DB_ROOT_USER}                                         \
        ${DB_ROOT_PASSWORD}                                     \
        ${ICINGAWEB2_MODULE_DIRECTOR_DB_DATABASE}               \
        ${ICINGAWEB2_MODULE_DIRECTOR_DB_CHARSET}		\
        "/usr/share/icingaweb2/modules/director/schema/${ICINGAWEB2_MODULE_DIRECTOR_DB_TYPE}.sql"
# Create director user
db_create_user                                                  \
        ${ICINGAWEB2_DB_HOST}                                   \
        ${ICINGAWEB2_DB_PORT}                                   \
        ${DB_ROOT_USER}                                         \
        ${DB_ROOT_PASSWORD}                                     \
        ${ICINGAWEB2_MODULE_DIRECTOR_DB_DATABASE}               \
        ${ICINGAWEB2_MODULE_DIRECTOR_DB_USER}                   \
        ${ICINGAWEB2_MODULE_DIRECTOR_DB_PASSWORD}

cat > "$PATH_ICINGAWEB2/resources.2.ini" <<-END

[director]
type = "db"
db = "${ICINGAWEB2_MODULE_DIRECTOR_DB_TYPE}"
host = "${ICINGAWEB2_MODULE_DIRECTOR_DB_HOST}"
port = "${ICINGAWEB2_MODULE_DIRECTOR_DB_PORT}"
dbname = "${ICINGAWEB2_MODULE_DIRECTOR_DB_DATABASE}"
username = "${ICINGAWEB2_MODULE_DIRECTOR_DB_USER}"
password = "${ICINGAWEB2_MODULE_DIRECTOR_DB_PASSWORD}"
charset = "${ICINGAWEB2_MODULE_DIRECTOR_DB_CHARSET}"
persistent = "${ICINGAWEB2_MODULE_DIRECTOR_DB_PERSISTENT}"
use_ssl = "${ICINGAWEB2_MODULE_DIRECTOR_DB_USE_SSL}"
END


cat "$PATH_ICINGAWEB2/resources.1.ini" "$PATH_ICINGAWEB2/resources.2.ini" > "$PATH_ICINGAWEB2/resources.ini"
rm -rf "$PATH_ICINGAWEB2/resources.2.ini"

cat > "$PATH_ICINGA2/conf.d/icinga2-api-user.conf" <<-END
object ApiUser "${ICINGA2_API_DIRECTOR_USER}" {
    password = "${ICINGA2_API_DIRECTOR_PASSWORD}"
    permissions = [ "*" ]
}
END

cat > "$PATH_ICINGAWEB2/modules/director/kickstart.ini" <<-END
[config]
endpoint = icinga-master
; host = 127.0.0.1
; port = 5665
username = ${ICINGA2_API_DIRECTOR_USER}
password = ${ICINGA2_API_DIRECTOR_PASSWORD}
END

icingacli module enable director

icingacli director kickstart run

echo "=>Icinga2 Director setup [OK]"

