version: '3'

services:
  icingaweb2:
    build:
      context: ../../image
    container_name: icinga_web
    restart: "unless-stopped"
    environment:
      - ICINGAWEB2_DB_DATABASE=icingaweb2
      - ICINGAWEB2_DB_USER=icingaweb2
      - ICINGAWEB2_DB_PASSWORD=QHWlggblWsHk2tjQzQOv
      - ICINGAWEB2_DB_CHARSET=latin1
      - ICINGAWEB2_DB_USE_SSL=0
      - ICINGAWEB2_ADMIN_USER=icingaadmin
      - ICINGAWEB2_ADMIN_PASSWORD=changeme
      - ICINGA2_DB_IDO_DATABASE=icinga_ido
      - ICINGA2_DB_IDO_USER=icinga_ido
      - ICINGA2_DB_IDO_PASSWORD=CJQwDN64ZgmDEPjLqXrU
      - PHP_TIMEZONE=Europe/Paris
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_ROOT_USER=postgres
      - DB_ROOT_PASSWORD=06ks9Ugo0wjHtleSNe96
    volumes:
      - ./icinga/etc/icinga2:/etc/icinga2
      - ./icinga/etc/icingaweb2:/etc/icingaweb2
      - ./icinga/log:/var/log
    ports:
      - "8080:80"
      - "8443:443"
      - "5665:5665"
  postgres:
    image: postgres:latest
    container_name: icinga_db
    restart: "unless-stopped"
    environment:
      - "POSTGRES_PASSWORD=06ks9Ugo0wjHtleSNe96"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
